package com.example.letsconnect.network

import kotlinx.serialization.Serializable

@Serializable
data class ExposedUser(
    val id: UInt,
    val fullName: String,
    val username: String,
    val password: String? = null
)

// 1. New payload model used to send the Google ID Token to your Ktor backend
@Serializable
data class GoogleLoginRequest(
    val idToken: String
)

@Serializable
data class LoginRequest(
    val username: String,
    val password: String
)

@Serializable
data class SignUpRequest(
    val fullName: String,
    val username: String,
    val password: String
)

// 2. Updated to include the custom JWT session token generated by your Ktor server
@Serializable
data class AuthResponse(
    val id: UInt,
    val fullName: String,
    val username: String,
    val message: String? = null,
    val token: String?=null // 👈 Added to capture the authentication token sent back by the backend
)

@Serializable
data class ErrorResponse(
    val error: String
)

@Serializable
data class Message(
    val id: UInt? = null,
    val senderId: UInt,
    val receiverId: UInt,
    val content: String,
    val timestamp: String,
    val isRead: Boolean = false
)

@Serializable
data class SendMessageRequest(
    val senderId: UInt,
    val receiverId: UInt,
    val content: String
)

@Serializable
data class UpdateMessageRequest(
    val content: String
)
